/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JanelaAdicionaCliente.java
 *
 * Created on Apr 8, 2011, 6:50:48 PM
 */

package petshop.gui;

/**
 *
 * @author arthur
 */
public class JanelaAdicionaCliente extends JanelaAdiciona {

    /** Creates new form JanelaAdicionaCliente */
    public JanelaAdicionaCliente() {
        initComponents();

        setTitle("Adicionar Cliente");
        setModelo(new String[] { "Código", "Nome", "Espécie", "Raça" });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cliente");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaAdicionaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
