/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JanelaCadastroCliente.java
 *
 * Created on Apr 7, 2011, 8:19:40 AM
 */

package petshop.gui;

import javax.swing.JOptionPane;
import javax.swing.text.JTextComponent;

/**
 *
 * @author arthur
 */
public class JanelaCadastroCliente extends javax.swing.JDialog {

    /** Creates new form JanelaCadastroCliente */
    public JanelaCadastroCliente() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        campoNome = new javax.swing.JTextField();
        comboSexo = new javax.swing.JComboBox();
        campoTelefone = new javax.swing.JTextField();
        campoCelular = new javax.swing.JTextField();
        campoEndereco = new javax.swing.JTextField();
        campoNumero = new javax.swing.JTextField();
        campoComplemento = new javax.swing.JTextField();
        campoBairro = new javax.swing.JTextField();
        campoCidade = new javax.swing.JTextField();
        comboUF = new javax.swing.JComboBox();
        campoCEP = new javax.swing.JTextField();
        campoRG = new javax.swing.JTextField();
        campoCPF = new javax.swing.JTextField();
        campoEMail = new javax.swing.JTextField();
        scrollInformacoes = new javax.swing.JScrollPane();
        areaInformacoes = new javax.swing.JTextArea();
        botaoLimpar = new javax.swing.JButton();
        botaoCadastrar = new javax.swing.JButton();
        comboAnimais = new javax.swing.JComboBox();
        botaoAddAnimal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        campoNome.setText("Nome");
        campoNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoNomecampoPerdeEtiqueta(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoNomecampoRetornaEtiqueta(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 250;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        jPanel1.add(campoNome, gridBagConstraints);

        comboSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sexo", "Masculino", "Feminino" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        jPanel1.add(comboSexo, gridBagConstraints);

        campoTelefone.setText("Telefone");
        campoTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoTelefonecampoPerdeEtiqueta(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoTelefonecampoRetornaEtiqueta(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 10);
        jPanel1.add(campoTelefone, gridBagConstraints);

        campoCelular.setText("Celular");
        campoCelular.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoCelularcampoPerdeEtiqueta(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCelularcampoRetornaEtiqueta(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        jPanel1.add(campoCelular, gridBagConstraints);

        campoEndereco.setText("Endereço");
        campoEndereco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoEnderecocampoPerdeEtiqueta(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoEnderecocampoRetornaEtiqueta(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 10);
        jPanel1.add(campoEndereco, gridBagConstraints);

        campoNumero.setText("Número");
        campoNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoNumerocampoPerdeEtiqueta(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoNumerocampoRetornaEtiqueta(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        jPanel1.add(campoNumero, gridBagConstraints);

        campoComplemento.setText("Complemento");
        campoComplemento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoComplementocampoPerdeEtiqueta(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoComplementocampoRetornaEtiqueta(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 10);
        jPanel1.add(campoComplemento, gridBagConstraints);

        campoBairro.setText("Bairro");
        campoBairro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoBairrocampoPerdeEtiqueta(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoBairrocampoRetornaEtiqueta(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 10);
        jPanel1.add(campoBairro, gridBagConstraints);

        campoCidade.setText("Cidade");
        campoCidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoCidadecampoPerdeEtiqueta(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCidadecampoRetornaEtiqueta(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 170;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        jPanel1.add(campoCidade, gridBagConstraints);

        comboUF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "UF", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "GO", "ES", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SP", "SC", "SE", "TO" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 10);
        jPanel1.add(comboUF, gridBagConstraints);

        campoCEP.setText("CEP");
        campoCEP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoCEPcampoPerdeEtiqueta(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCEPcampoRetornaEtiqueta(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 10);
        jPanel1.add(campoCEP, gridBagConstraints);

        campoRG.setText("RG");
        campoRG.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoRGcampoPerdeEtiqueta(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoRGcampoRetornaEtiqueta(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 120;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        jPanel1.add(campoRG, gridBagConstraints);

        campoCPF.setText("CPF");
        campoCPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoCPFcampoPerdeEtiqueta(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCPFcampoRetornaEtiqueta(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 170;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 10);
        jPanel1.add(campoCPF, gridBagConstraints);

        campoEMail.setText("e-Mail");
        campoEMail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoEMailcampoPerdeEtiqueta(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoEMailcampoRetornaEtiqueta(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        jPanel1.add(campoEMail, gridBagConstraints);

        areaInformacoes.setColumns(20);
        areaInformacoes.setRows(5);
        areaInformacoes.setText("Informações Adicionais");
        areaInformacoes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                areaInformacoescampoPerdeEtiqueta(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                areaInformacoescampoRetornaEtiqueta(evt);
            }
        });
        scrollInformacoes.setViewportView(areaInformacoes);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 30;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        jPanel1.add(scrollInformacoes, gridBagConstraints);

        botaoLimpar.setText("Limpar");
        botaoLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoLimparlimparCampos(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(botaoLimpar, gridBagConstraints);

        botaoCadastrar.setText("Cadastrar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(botaoCadastrar, gridBagConstraints);

        comboAnimais.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Animais" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(comboAnimais, gridBagConstraints);

        botaoAddAnimal.setText("Adicionar");
        botaoAddAnimal.setMinimumSize(null);
        botaoAddAnimal.setPreferredSize(null);
        botaoAddAnimal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoAddAnimalMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 10);
        jPanel1.add(botaoAddAnimal, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNomecampoPerdeEtiqueta(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNomecampoPerdeEtiqueta
        JTextComponent campo = (JTextComponent) evt.getComponent();

        if(campo.getText().equals(getEtiqueta(campo))){
            campo.setText("");
        }
}//GEN-LAST:event_campoNomecampoPerdeEtiqueta

    private void campoNomecampoRetornaEtiqueta(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNomecampoRetornaEtiqueta
        JTextComponent campo = (JTextComponent) evt.getComponent();

        if(campo.getText().equals("")){
            campo.setText(getEtiqueta(campo));
        }
}//GEN-LAST:event_campoNomecampoRetornaEtiqueta

    private void campoTelefonecampoPerdeEtiqueta(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoTelefonecampoPerdeEtiqueta
        JTextComponent campo = (JTextComponent) evt.getComponent();

        if(campo.getText().equals(getEtiqueta(campo))){
            campo.setText("");
        }
}//GEN-LAST:event_campoTelefonecampoPerdeEtiqueta

    private void campoTelefonecampoRetornaEtiqueta(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoTelefonecampoRetornaEtiqueta
        JTextComponent campo = (JTextComponent) evt.getComponent();

        if(campo.getText().equals("")){
            campo.setText(getEtiqueta(campo));
        }
}//GEN-LAST:event_campoTelefonecampoRetornaEtiqueta

    private void campoCelularcampoPerdeEtiqueta(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCelularcampoPerdeEtiqueta
        JTextComponent campo = (JTextComponent) evt.getComponent();

        if(campo.getText().equals(getEtiqueta(campo))){
            campo.setText("");
        }
}//GEN-LAST:event_campoCelularcampoPerdeEtiqueta

    private void campoCelularcampoRetornaEtiqueta(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCelularcampoRetornaEtiqueta
        JTextComponent campo = (JTextComponent) evt.getComponent();

        if(campo.getText().equals("")){
            campo.setText(getEtiqueta(campo));
        }
}//GEN-LAST:event_campoCelularcampoRetornaEtiqueta

    private void campoEnderecocampoPerdeEtiqueta(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEnderecocampoPerdeEtiqueta
        JTextComponent campo = (JTextComponent) evt.getComponent();

        if(campo.getText().equals(getEtiqueta(campo))){
            campo.setText("");
        }
}//GEN-LAST:event_campoEnderecocampoPerdeEtiqueta

    private void campoEnderecocampoRetornaEtiqueta(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEnderecocampoRetornaEtiqueta
        JTextComponent campo = (JTextComponent) evt.getComponent();

        if(campo.getText().equals("")){
            campo.setText(getEtiqueta(campo));
        }
}//GEN-LAST:event_campoEnderecocampoRetornaEtiqueta

    private void campoNumerocampoPerdeEtiqueta(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNumerocampoPerdeEtiqueta
        JTextComponent campo = (JTextComponent) evt.getComponent();

        if(campo.getText().equals(getEtiqueta(campo))){
            campo.setText("");
        }
}//GEN-LAST:event_campoNumerocampoPerdeEtiqueta

    private void campoNumerocampoRetornaEtiqueta(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNumerocampoRetornaEtiqueta
        JTextComponent campo = (JTextComponent) evt.getComponent();

        if(campo.getText().equals("")){
            campo.setText(getEtiqueta(campo));
        }
}//GEN-LAST:event_campoNumerocampoRetornaEtiqueta

    private void campoComplementocampoPerdeEtiqueta(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoComplementocampoPerdeEtiqueta
        JTextComponent campo = (JTextComponent) evt.getComponent();

        if(campo.getText().equals(getEtiqueta(campo))){
            campo.setText("");
        }
}//GEN-LAST:event_campoComplementocampoPerdeEtiqueta

    private void campoComplementocampoRetornaEtiqueta(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoComplementocampoRetornaEtiqueta
        JTextComponent campo = (JTextComponent) evt.getComponent();

        if(campo.getText().equals("")){
            campo.setText(getEtiqueta(campo));
        }
}//GEN-LAST:event_campoComplementocampoRetornaEtiqueta

    private void campoBairrocampoPerdeEtiqueta(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoBairrocampoPerdeEtiqueta
        JTextComponent campo = (JTextComponent) evt.getComponent();

        if(campo.getText().equals(getEtiqueta(campo))){
            campo.setText("");
        }
}//GEN-LAST:event_campoBairrocampoPerdeEtiqueta

    private void campoBairrocampoRetornaEtiqueta(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoBairrocampoRetornaEtiqueta
        JTextComponent campo = (JTextComponent) evt.getComponent();

        if(campo.getText().equals("")){
            campo.setText(getEtiqueta(campo));
        }
}//GEN-LAST:event_campoBairrocampoRetornaEtiqueta

    private void campoCidadecampoPerdeEtiqueta(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCidadecampoPerdeEtiqueta
        JTextComponent campo = (JTextComponent) evt.getComponent();

        if(campo.getText().equals(getEtiqueta(campo))){
            campo.setText("");
        }
}//GEN-LAST:event_campoCidadecampoPerdeEtiqueta

    private void campoCidadecampoRetornaEtiqueta(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCidadecampoRetornaEtiqueta
        JTextComponent campo = (JTextComponent) evt.getComponent();

        if(campo.getText().equals("")){
            campo.setText(getEtiqueta(campo));
        }
}//GEN-LAST:event_campoCidadecampoRetornaEtiqueta

    private void campoCEPcampoPerdeEtiqueta(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCEPcampoPerdeEtiqueta
        JTextComponent campo = (JTextComponent) evt.getComponent();

        if(campo.getText().equals(getEtiqueta(campo))){
            campo.setText("");
        }
}//GEN-LAST:event_campoCEPcampoPerdeEtiqueta

    private void campoCEPcampoRetornaEtiqueta(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCEPcampoRetornaEtiqueta
        JTextComponent campo = (JTextComponent) evt.getComponent();

        if(campo.getText().equals("")){
            campo.setText(getEtiqueta(campo));
        }
}//GEN-LAST:event_campoCEPcampoRetornaEtiqueta

    private void campoRGcampoPerdeEtiqueta(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoRGcampoPerdeEtiqueta
        JTextComponent campo = (JTextComponent) evt.getComponent();

        if(campo.getText().equals(getEtiqueta(campo))){
            campo.setText("");
        }
}//GEN-LAST:event_campoRGcampoPerdeEtiqueta

    private void campoRGcampoRetornaEtiqueta(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoRGcampoRetornaEtiqueta
        JTextComponent campo = (JTextComponent) evt.getComponent();

        if(campo.getText().equals("")){
            campo.setText(getEtiqueta(campo));
        }
}//GEN-LAST:event_campoRGcampoRetornaEtiqueta

    private void campoCPFcampoPerdeEtiqueta(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCPFcampoPerdeEtiqueta
        JTextComponent campo = (JTextComponent) evt.getComponent();

        if(campo.getText().equals(getEtiqueta(campo))){
            campo.setText("");
        }
}//GEN-LAST:event_campoCPFcampoPerdeEtiqueta

    private void campoCPFcampoRetornaEtiqueta(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCPFcampoRetornaEtiqueta
        JTextComponent campo = (JTextComponent) evt.getComponent();

        if(campo.getText().equals("")){
            campo.setText(getEtiqueta(campo));
        }
}//GEN-LAST:event_campoCPFcampoRetornaEtiqueta

    private void campoEMailcampoPerdeEtiqueta(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEMailcampoPerdeEtiqueta
        JTextComponent campo = (JTextComponent) evt.getComponent();

        if(campo.getText().equals(getEtiqueta(campo))){
            campo.setText("");
        }
}//GEN-LAST:event_campoEMailcampoPerdeEtiqueta

    private void campoEMailcampoRetornaEtiqueta(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEMailcampoRetornaEtiqueta
        JTextComponent campo = (JTextComponent) evt.getComponent();

        if(campo.getText().equals("")){
            campo.setText(getEtiqueta(campo));
        }
}//GEN-LAST:event_campoEMailcampoRetornaEtiqueta

    private void areaInformacoescampoPerdeEtiqueta(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_areaInformacoescampoPerdeEtiqueta
        JTextComponent campo = (JTextComponent) evt.getComponent();

        if(campo.getText().equals(getEtiqueta(campo))){
            campo.setText("");
        }
}//GEN-LAST:event_areaInformacoescampoPerdeEtiqueta

    private void areaInformacoescampoRetornaEtiqueta(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_areaInformacoescampoRetornaEtiqueta
        JTextComponent campo = (JTextComponent) evt.getComponent();

        if(campo.getText().equals("")){
            campo.setText(getEtiqueta(campo));
        }
}//GEN-LAST:event_areaInformacoescampoRetornaEtiqueta

    private void botaoLimparlimparCampos(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoLimparlimparCampos

        int resp = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja limpar todos os campos?", "Sair", JOptionPane.YES_NO_OPTION);

        if(resp == JOptionPane.YES_OPTION)
            limparCampos();
}//GEN-LAST:event_botaoLimparlimparCampos

    private void botaoAddAnimalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoAddAnimalMouseClicked
        JanelaCadastroAnimal animal = new JanelaCadastroAnimal();

        animal.setModalityType(java.awt.Dialog.DEFAULT_MODALITY_TYPE);
        animal.setVisible(true);
}//GEN-LAST:event_botaoAddAnimalMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaCadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaInformacoes;
    private javax.swing.JButton botaoAddAnimal;
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JTextField campoBairro;
    private javax.swing.JTextField campoCEP;
    private javax.swing.JTextField campoCPF;
    private javax.swing.JTextField campoCelular;
    private javax.swing.JTextField campoCidade;
    private javax.swing.JTextField campoComplemento;
    private javax.swing.JTextField campoEMail;
    private javax.swing.JTextField campoEndereco;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoNumero;
    private javax.swing.JTextField campoRG;
    private javax.swing.JTextField campoTelefone;
    private javax.swing.JComboBox comboAnimais;
    private javax.swing.JComboBox comboSexo;
    private javax.swing.JComboBox comboUF;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane scrollInformacoes;
    // End of variables declaration//GEN-END:variables



    private String getEtiqueta(JTextComponent campo){

        if(campo.equals(campoNome)) return "Nome";
        else if(campo.equals(campoEndereco)) return "Endereço";
        else if(campo.equals(campoNumero)) return "Número";
        else if(campo.equals(campoComplemento)) return "Complemento";
        else if(campo.equals(campoBairro)) return "Bairro";
        else if(campo.equals(campoCidade)) return "Cidade";
        else if(campo.equals(campoCEP)) return "CEP";
        else if(campo.equals(campoRG)) return "RG";
        else if(campo.equals(campoCPF)) return "CPF";
        else if(campo.equals(campoEMail)) return "e-Mail";
        else if(campo.equals(campoTelefone)) return "Telefone";
        else if(campo.equals(campoCelular)) return "Celular";
        else if(campo.equals(areaInformacoes)) return "Informações Adicionais";

        return "";
    }


    private void limparCampos(){

        campoNome.setText("Nome");
        comboSexo.setSelectedIndex(0);
        campoEndereco.setText("Endereco");
        campoNumero.setText("Numero");
        campoComplemento.setText("Complemento");
        campoBairro.setText("Bairro");
        campoCidade.setText("Cidade");
        comboUF.setSelectedIndex(0);
        campoCEP.setText("CEP");
        campoRG.setText("RG");
        campoCPF.setText("CPF");
        campoEMail.setText("e-Mail");
        campoTelefone.setText("Telefone");
        campoCelular.setText("Celular");
        comboAnimais.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Animais"}));
        areaInformacoes.setText("Informações Adicionais");
    }
}
